### PR TITLE
feat: allow neuro to explain & fix linting errors, like copilot

### LINKED ISSUE #25: Let Neuro fix linting problems
Don't know if this is possible, but would likely require proposed API. When you press `Ctrl+.` on a linting problem, there is an option to let copilot fix it, what we want is to let Neuro fix it instead. This shouldn't require Autopilot, since GitHub Copilot can do this too, there must some syntax to this.

### PR DESCRIPTION
**Pull request by KTrain5169**
I don't know what I'm doing so I'll just open this draft now and maybe deal with it later

resolves #25 

This adds to the Copilot side of NeuroPilot by adding the `Ask Neuro to fix` and `Ask Neuro to explain` buttons to lint errors.

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -35,6 +37,143 @@ export function activate(context: vscode.ExtensionContext) {
...
+        const response = await requestAIResponseForDiagnostic(document, diagnostic, 'explain', tokenSource.token);
+
+        // Append the response to the chat history.
+        addToChatHistory("Explain: " + response);
+        // Show an info message with an option to view the chat history.
+        const choice = await vscode.window.showInformationMessage("Neuro explains: " + response, "View Chat History");
+        if (choice === "View Chat History") {
+            chatHistoryChannel.show();
+        }
+    });
```
Comment (Pasu4) [inline src/extension.ts:114]: This takes up too much space in `activate`, the lambdas should be extracted into functions (lint_problems.ts?)

File: src/extension.ts [hunk 2]
```diff
@@ -35,6 +37,143 @@ export function activate(context: vscode.ExtensionContext) {
...
+                actions.push(explain);
+            });
+
+            return actions;
+            }
+        })(),
+        {
+            providedCodeActionKinds: [vscode.CodeActionKind.QuickFix]
+        }
+    );
```
Comment (Pasu4) [inline src/extension.ts:174]: I don't quite understand what this does at the moment (1:30 AM brain), but if possible extract from `activate`.

**Review by Pasu4 — CHANGES_REQUESTED** [review]
Didn't do any testing, just looked over the code real quick, I'll do a proper review tomorrow.

**Review by Pasu4 — APPROVED** [review]
